# CachyOS ships a default fish config; only source it where it exists (not on Ubuntu/GNOME).
if test -f /usr/share/cachyos-fish-config/cachyos-config.fish
    source /usr/share/cachyos-fish-config/cachyos-config.fish
end

# Theme: point starship at the generated palette (written by `theme-switch`).
# Must be set before `starship init`. Falls back to the committed config if the
# theme file doesn't exist yet.
if test -f "$HOME/.config/theme/starship.toml"
    set -gx STARSHIP_CONFIG "$HOME/.config/theme/starship.toml"
end

starship init fish | source

# tmuxifier (only if installed)
set -x TMUXIFIER_LAYOUT_PATH "$HOME/.tmuxifier/layouts"
if test -f "$HOME/.tmuxifier/init.fish"
    source "$HOME/.tmuxifier/init.fish"

    function load
        tmuxifier load-session $argv
    end
end

# opencode (only if installed)
if test -d "$HOME/.opencode/bin"
    fish_add_path "$HOME/.opencode/bin"
end

# zoxide — smarter cd (only if installed)
if type -q zoxide
    zoxide init fish | source
end

# fzf — theme colors generated by `theme-switch` (applies to new shells)
if test -f "$HOME/.config/theme/fzf.fish"
    source "$HOME/.config/theme/fzf.fish"
end
