return {
  {
    "folke/snacks.nvim",
    opts = {
      picker = {
        sources = {
          explorer = {
            hidden = true,
            ignored = true,
            exclude = {
              "node_modules",
              ".git",
              ".next",
              ".turbo",
              ".vercel",
              "out",
              "__pycache__",
              ".venv",
              "venv",
              ".mypy_cache",
              ".pytest_cache",
              ".ruff_cache",
              "target",
              "obj",
            },
          },
          files = {
            hidden = true,
            ignored = true,
            exclude = {
              "node_modules",
              ".git",
              ".next",
              ".turbo",
              ".vercel",
              "out",
              "__pycache__",
              ".venv",
              "venv",
              ".mypy_cache",
              ".pytest_cache",
              ".ruff_cache",
              "target",
              "obj",
            },
          },
          grep = {
            hidden = true,
            ignored = true,
            exclude = {
              "node_modules",
              ".git",
              ".next",
              ".turbo",
              ".vercel",
              "out",
              "__pycache__",
              ".venv",
              "venv",
              ".mypy_cache",
              ".pytest_cache",
              ".ruff_cache",
              "target",
              "obj",
            },
          },
        },
      },
    },
  },
}
